### PR TITLE
example: add complete federation v2 example

### PR DESCRIPTION
**Pull request by meekdenzo**
This adds a complete working example of federation v2.

### CODE REVIEW

**Comment by meekdenzo** [comment]
@TriPSs can I get some help here? I don't have a lot of experience with nx, and I don't understand why the e2e tests are failing with `yarn nx e2e examples` but passing with `pnpm run test:e2e --testPathPattern=PATH_TO_FEDERATION_2_EXAMPLE`. Also, I'm seeing test failures in the examples I didn't even touch.

**Comment by TriPSs** [comment]
If I look at the CI that is failing I see that it all tests from "Federated" with the error:
```
    GraphQLSchemaValidationError: Unknown directive "@link".
```

**Comment by meekdenzo** [comment]
So after close inspection of the error logs (running locally), I see that the failing tests are from some other examples:

`pnpm run test:e2e --testPathPattern=/Users/meekdenzo/projects/open-source/nestjs-query/examples/federation-2`

image

`pnpm nx e2e examples`

image

Can you please run the tests from your end and confirm if there are issues in the other examples?

**Comment by meekdenzo** [comment]
So far I have identified:

> Error: No AuthorizationContext available for method failingTodoItems! Make sure that you provide an AuthorizationContext to your custom methods as argument of the @AuthorizerFilter decorator.

and 

> Error: Unable to find todoItem to set on SubTaskEntity

from

`pnpm run test:e2e --testPathPattern=/Users/meekdenzo/projects/open-source/nestjs-query/examples/auth`

image

**Comment by meekdenzo** [comment]
> If I look at the CI that is failing I see that it all tests from "Federated" with the error:
> 
> ```
>     GraphQLSchemaValidationError: Unknown directive "@link".
> ```

I think this is because of the `@apollo/subgraph` dep. I see we don't have it in the current package.json. I wonder why this isn't the case locally

**Comment by TriPSs** [comment]
Thanks for the PR, checkout the issues and fixed them with #189.

**Pull request merged**
