### PR TITLE
Fix a bug for TypeORM relations

### PR DESCRIPTION
**Pull request by jpv-os**
Based on the discussion in this issue: https://github.com/TriPSs/nestjs-query/issues/115

### CODE REVIEW

**Comment by jpv-os** [comment]
Fixed lint errors, amended commit, pushed again

**Comment by jpv-os** [comment]
> ## [Codecov](https://app.codecov.io/gh/TriPSs/nestjs-query/pull/175?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tycho+Bokdam) Report
> > Merging [#175](https://app.codecov.io/gh/TriPSs/nestjs-query/pull/175?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tycho+Bokdam) ([96d6060](https://github.com/TriPSs/nestjs-query/commit/96d6060d2657de5341bfaf79c5c31bdfc17153c9)) into [master](https://app.codecov.io/gh/TriPSs/nestjs-query/commit/dddced2379481cb2ac97fab92006796d5911e18e?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tycho+Bokdam) ([dddced2](https://github.com/TriPSs/nestjs-query/commit/dddced2379481cb2ac97fab92006796d5911e18e)) will **decrease** coverage by `7.55%`.
> > The diff coverage is `100.00%`.
> 
> ```diff
> @@            Coverage Diff             @@
> ##           master     #175      +/-   ##
> ==========================================
> - Coverage   86.09%   78.55%   -7.55%     
> ==========================================
>   Files         625      625              
>   Lines        9154     9157       +3     
>   Branches      838      838              
> ==========================================
> - Hits         7881     7193     -688     
> - Misses        567     1230     +663     
> - Partials      706      734      +28     
> ```
> 
> [Files Changed](https://app.codecov.io/gh/TriPSs/nestjs-query/pull/175?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tycho+Bokdam)	Coverage Δ	
> [.../query-typeorm/src/query/relation-query.builder.ts](https://app.codecov.io/gh/TriPSs/nestjs-query/pull/175?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tycho+Bokdam#diff-cGFja2FnZXMvcXVlcnktdHlwZW9ybS9zcmMvcXVlcnkvcmVsYXRpb24tcXVlcnkuYnVpbGRlci50cw==)	`90.69% <100.00%> (-4.57%)`	⬇️
> ... and [82 files with indirect coverage changes](https://app.codecov.io/gh/TriPSs/nestjs-query/pull/175/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tycho+Bokdam)
> 
> 📣 We’re building smart automated test selection to slash your CI/CD build times. [Learn more](https://about.codecov.io/iterative-testing/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Tycho+Bokdam)

This report does not seem to match the code coverage generated by running `nx run query-typeorm:test --coverage`, which is what I did. There are plenty of test hits for the lines of code that I touched. So how should I react to this automated report?

**Comment by TriPSs** [comment]
@jpv-os no you can ignore that, I think in PR's it does not always reflect it properly.

Before I merge this I want to check this with my projects if you don't mind, hope to do that this week.

**Comment by jpv-os** [comment]
Sure! Thanks a lot. Actually there still is a lint error, which is why I pushed again (IDE inserted semicolon when fixing the last lint error)

**Comment by jpv-os** [comment]
How is it going @TriPSs ?

**Comment by TriPSs** [comment]
My apologies! I'm going to check tomorrow and will let you know!

**Comment by TriPSs** [comment]
Thanks for the PR, checkt quickly and did not see anything weird!

**Comment by TriPSs** [comment]
@jpv-os sadly this PR did contain changes that broke a part of my production API, therefore I created a PR that changes the implementation (same way we do many to many relations).

Could you check if these changes also work for you? It's released as `4.2.1-alpha.2`

**Pull request merged**
