### PR TITLE
Fix typegoose tests and other improvements

### PR DESCRIPTION
**Pull request by smolinari**
Hi @TriPSs,

I did a lot of work unfortunately in this one commit on the query-typegoose package (and others). I started working on the e2e tests, then noticed a ton of unit tests were commented out. Uncommented them and then one thing continued to lead to the other. 

At any rate, here is a list of the main changes:

1. Fixed the issue with query-typegoose and class-transformer (causing the unit tests to fail). 
2. Fixed any broken e2e tests. 
3. Updated the Mongo Memory Server to the newest version. 
4. Updated TypeScript to 4.8.4 along with updating Nest versions too.

Note: I tried to get the mongoose e2e tests going, but there are 5 still failing and I had to stop troubleshooting due to lack of time. So, it is back in the `/disabled` folder. I'm also more concerned with Typegoose's implementation, sorry. :shrug: All of the mongoose unit tests are working though. 

If you agree this is all ok, I'll also update the docs to include the new `@ObjectId` decorator for Typegoose entities. 

Scott

### CODE REVIEW

**Comment by TriPSs** [comment]
Thanks for the PR! Let me know when the docs are updated then we can merge this.

**Comment by smolinari** [comment]
@TriPSs - Ok. Cool. And done. I also fixed the failing linting too, I think. :grin: 

Scott

**Comment by smolinari** [comment]
Glad you hadn't merged this yet. I just coincidentally found that I had forgotten to save a file I changed in the docs. DOH!!!

Scott

**Comment by smolinari** [comment]
From my point of view, this is ready to merge. 

Scott

**Pull request merged**
