### PR TITLE
fix(query-typeorm): name collision on deeply nested filters

### PR DESCRIPTION
**Pull request by hedwiggggg**
This branch fixes the name collision on the relation-joins. The following query for example would fail, because the generated JOIN-statements were named after the filter-properties.

```graphql
{
  users(
    filter: {
      posts: {
        categories: {
          posts: {
            title: {
              eq: "Post 1"
            }
          }
        }

        authors: {
          posts: {
            title: {
              eq: "Post 1"
            }
          }
        }
      }
    }
  ) {
    id
    firstName
    lastName
  }
}
```

`users -> posts` is a join
`(users -> posts ->) categories -> posts` is another join
`(users -> posts ->) authors -> posts` is another join

For all this joins only the name `posts` was used. `join "post" "posts" on ...` which would lead to the sql error `table name "posts" specified more than once`.

### CODE REVIEW

**Comment by hedwiggggg** [comment]
This PR includes the changes from https://github.com/TriPSs/nestjs-query/pull/143.

**Comment by hedwiggggg** [comment]
This is not ready yet, found a bug using this fix. I will report as soon as I know more.

**Comment by hedwiggggg** [comment]
Okay there are two issues i noticed using this in our development environment. The first one is related to this fix, the second one seems to be a bug in the `filter-query.builder.ts`.

#### First issue
I count the occurences of the relations, both in the `applyRelationJoinsRecursive`, and in the `WhereBuilder`. The problem is, that I don't respect, if it is a new join or not in the `WhereBuilder`. So a filter like this:
```
{
  or: [
    { users: { email: { eq: "user1@example.org" } } },
    { users: { email: { eq: "user2@example.org" } } },
  ],
}
```
will result in a wrong alias, that get's used by the `WhereBuilder`. Should be a relatively easy fix.

#### Second issue
This is related to the `filter-query.builder.ts`. Querying will generate a `SELECT`, not a `SELECT DISTINCT`. This will lead to a lot of duplicate entries, especially when applying deep filters.

image

**Comment by hedwiggggg** [comment]
I fixed the first issue, but fixing the second issue made some tests fail, because of deviating snapshots and some deep equality expects that failed. That is not too urgent for us to be fixed, so i would tackle this issue in another PR after this one got merged.

**Comment by TriPSs** [comment]
Thanks for the fix!

**Pull request merged**
