### PR TITLE
fix: fix wrong mapping when the relation is one to one or ont to many…

### PR DESCRIPTION
**Pull request by mahmoudzeyada**
… not owned
there was a problem when making the filtration of resolved relations,

description :
1- suppose we have a user Dto and profile Dto (one-to-one relation)
2- when we ask for a profile at user Dto it gives an error that can not set nullable for non-nullable filed 
 why this happened because it depends on filtering all the resolved profile entities on some attributes that do not exist in that entity basically depending on this method `column.propertyName` which determines to user not profile_user_id !!
 
 this commit solves this issue by filtering the raw data first then getting the matched times 
 hint (previously the main package does not give this error )

### CODE REVIEW

**Comment by TriPSs** [comment]
> hint (previously the main package does not give this error )

This could be correct, I rewrote these parts so they perform better on larger data sets (the original implementation was fine for 1-5 records, not 50)

**Comment by mahmoudzeyada** [comment]
Yes, but The problem is not that , i think the problem is how the mapping is working the previous one is working fine but after your enhancement it doesn't work anymore when i added this fix everything worked again

**Comment by estriv** [comment]
Hi,
I ran into this issue too.
You should be able to fix this by adding the relation id fields to the entities. Thereby no change has to be made and the current implementation stays small. I do not see a reason for adding a case for handling the id field not beeing present.

So:
```typescript
@ObjectType()
class Something {
  @Field()
  id: number;
  
  @OneToMany(() => [Relation], (rel) => rel.something)
  relations: Relation[];
}

@ObjectType()
class Relation {
  @Field()
  id: number;

  @Field()
  somethingId: number;
  
  @ManyToOne(() => Something, (st) => st.relations)
  something: Something;
}
```

**Comment by TriPSs** [comment]
Closing as @estriv gave a solution.

**Pull request closed without merging**
