### PR TITLE
Null sorting fix

### PR DESCRIPTION
**Pull request by abrenoch**
See https://github.com/TriPSs/nestjs-query/issues/270

### CODE REVIEW

**Comment by TriPSs** [comment]
@abrenoch the linting errors now could be fixed by running the linter with `--fix`. (Bit weird that Nx no longer outputs it here in the CI)

**Comment by abrenoch** [comment]
Hey @TriPSs does your nx cloud run say what the lint errors are? I'm trying to work out what is failing, even pointed the `nxCloudAccessToken` to a workspace I can check, and I'm seeing these "Buildable libraries cannot import or export from non-buildable libraries" errors when running `yarn nx run-many --target=lint --all` (adding `--fix` didnt seem to help).

 Could you provide some insight please? I have no idea what the issue here is.

**Comment by TriPSs** [comment]
@abrenoch reran the jobs and disabled that Nx does not output the logs here, bit weird that this was auto enabled.

**Comment by abrenoch** [comment]
Added a couple small changes the linter was complaining about - odd they were unrelated to the actual change I had made, but /shrug

**Comment by TriPSs** [comment]
Thanks for everything!

**Pull request merged**
