### PR TITLE
Hotfix/deps

### PR DESCRIPTION
**Pull request by qathom**
Hi @TriPSs 
I appreciate the initiative to make this project active, I think it is a library that has a lot of interest to exist.
I would like to participate in the development.
At the moment, I am trying to understand the structure of the project as well as possible.
In my opinion, the dependencies of each library such as `query-graphql`, `query-typeorm`, etc. should be moved to the respective package.json.
If it's right, I will continue moving the dependencies to `packages/query-*/package.json`

This PR is about moving dependencies of each package and upgrading them because it's not possible to install the library with the latest Nestjs packages (typeorm >= 0.3 / @nestjs/graphql >= 10)

### CODE REVIEW

**Comment by qathom** [comment]
Thanks! Not sure what's happening:
image

**Comment by qathom** [comment]
Yes, with cached modules:
`➤ YN0000: Done with warnings in 2s 351ms`

With clean install:
```
➤ YN0000: Completed in 49s 211ms
➤ YN0000: Done with warnings in 50s 735ms
```

**Comment by qathom** [comment]
Note: I refreshed yarn's lock file. Not sure if this can help.

**Comment by qathom** [comment]
I think that this is happening because I'm missing the "Maintainer" role in order to trigger these Github actions.
I tried to update all dependencies at once but it's harder than expected with the split of nestjs/graphql and nestjs/apollo.
I'm still on it :-)

**Comment by TriPSs** [comment]
Closing this one in favor of #26

**Pull request closed without merging**
