### PR TITLE
chore(deps):update mongoose peerDependencies

### PR DESCRIPTION
**Pull request by Doko-Demo-Doa**
Updates the peer dependencies of `query-mongoose` and `query-typegoose` so that they can be installed with latest mongoose version.

### CODE REVIEW

**Comment by Doko-Demo-Doa** [comment]
@TriPSs There are lots of `@typescript-eslint/no-unnecessary-type-assertion` linting issues, should I ignore them?

**Comment by TriPSs** [comment]
Yea, need to fix the linting.

**Comment by Doko-Demo-Doa** [comment]
Hi @TriPSs please can we make a release on npm for this one?

**Comment by TriPSs** [comment]
Yes ofc, sorry.

**Comment by Doko-Demo-Doa** [comment]
Thank you. It works greatly now!

**Pull request merged**
