### PR TITLE
fix(query-typegoose): update peer dependencies

### PR DESCRIPTION
**Pull request by smolinari**
Hi,

Not sure I did this right as I'm not experienced with Nx. Ran tests though and they all passed. 

I need this package updated to the newest versions of my `@m8a/nestjs-typegoose`, `@typegoose/typegoose` and `@mongoose` packages. 

Please do let me know if something is wrong. 

How fast can you publish a new version?

Scott

### CODE REVIEW

**Comment by TriPSs** [comment]
Thanks for the PR! I think the tests/linting needs to be update to support mongoose 7

**Comment by smolinari** [comment]
Interesting. I assumed testing did building too. Now I see the issues when building. LOL! I'm on it. Just not sure my TypeScript-fu is good enough to figure this out. We'll see. 

Scott

**Comment by smolinari** [comment]
I believe this also means, this would need to be a major bump in version too, right? :thinking: 

Scott

**Comment by TriPSs** [comment]
Uhmm, if it stays compatible with the old version then no otherwise yes :)

**Comment by smolinari** [comment]
@TriPSs - I hope it's good to go now. :grin:  

Scott

**Comment by smolinari** [comment]
@TriPSs - Sorry to be pushy, but is this ok and can you get the package updated?

Scott

**Comment by TriPSs** [comment]
> @TriPSs - Sorry to be pushy, but is this ok and can you get the package updated?
> 
> Scott

Could you check the last tests that are failing?

**Comment by smolinari** [comment]
@TriPSs - The errors seem to be issues with the Mongoose package. Should I update it too? 

Scott

**Comment by smolinari** [comment]
It's actually a mix of errors. The init script path for mongo is also broken. Had to fix it to run docker compose. 

I can look into the mongoose issues. But the other two are a bit out of my comfort zone. 

```
[Nest] 190142  - 04/05/2023, 1:14:10 PM   ERROR [ExceptionsHandler] No AuthorizationContext available for method failingTodoItems! Make sure that you provide an AuthorizationContext to your custom methods as argument of the @AuthorizerFilter decorator.
Error: No AuthorizationContext available for method failingTodoItems! Make sure that you provide an AuthorizationContext to your custom methods as argument of the @AuthorizerFilter decorator.
    at Object.get (/home/scott/Documents/tmp/nestjs-query-trips/packages/query-graphql/src/decorators/authorize-filter.decorator.ts:40:15)
    at Object.authorize (/home/scott/Documents/tmp/nestjs-query-trips/examples/auth/src/todo-item/dto/todo-item.dto.ts:23:28)
    at DefaultAuthorizer.authorize (/home/scott/Documents/tmp/nestjs-query-trips/packages/query-graphql/src/auth/default-crud.authorizer.ts:49:27)
    at getAuthorizerFilter (/home/scott/Documents/tmp/nestjs-query-trips/packages/query-graphql/src/decorators/authorize-filter.decorator.ts:19:29)
    at /home/scott/Documents/tmp/nestjs-query-trips/packages/query-graphql/src/decorators/authorize-filter.decorator.ts:59:7
    at /home/scott/Documents/tmp/nestjs-query-trips/node_modules/@nestjs/core/helpers/context-utils.js:40:28
    at resolveParamValue (/home/scott/Documents/tmp/nestjs-query-trips/node_modules/@nestjs/core/helpers/external-context-creator.js:138:31)
    at Array.map (<anonymous>)
    at pipesFn (/home/scott/Documents/tmp/nestjs-query-trips/node_modules/@nestjs/core/helpers/external-context-creator.js:141:45)
    at /home/scott/Documents/tmp/nestjs-query-trips/node_modules/@nestjs/core/helpers/external-context-creator.js:69:23
[Nest] 190142  - 04/05/2023, 1:14:11 PM   ERROR [ExceptionsHandler] Unable to find all subTasks to add to TodoItemEntity
Error: Unable to find all subTasks to add to TodoItemEntity
    at TypeOrmQueryService.addRelations (/home/scott/Documents/tmp/nestjs-query-trips/packages/query-typeorm/src/services/relation-query.service.ts:215:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TodoItemAssembler.convertAsyncToDTO (/home/scott/Documents/tmp/nestjs-query-trips/packages/core/src/assemblers/abstract.assembler.ts:64:15)

```
and

```
[Nest] 190142  - 04/05/2023, 1:14:33 PM   ERROR [ExceptionsHandler] Unable to find todoItem to set on SubTaskEntity
Error: Unable to find todoItem to set on SubTaskEntity
    at TypeOrmQueryService.setRelation (/home/scott/Documents/tmp/nestjs-query-trips/packages/query-typeorm/src/services/relation-query.service.ts:266:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DefaultAssembler.convertAsyncToDTO (/home/scott/Documents/tmp/nestjs-query-trips/packages/core/src/assemblers/abstract.assembler.ts:64:15)

```

Scott

**Comment by smolinari** [comment]
Hmm... strange. All tests showing passing. Ok. Nevermind. :grin: 

Scott

**Comment by smolinari** [comment]
Why is codecov failing? That is beyond me. :shrug: 

Scott

**Comment by TriPSs** [comment]
Thanks for the PR!

**Pull request merged**
